#!/bin/bash

MYIP=$(curl -sS ipv4.icanhazip.com)
domain=$(cat /etc/xray/domain)
dir="/etc/xnxx/"
log="/var/log/xray"
rycle="/etc/rycle"
sex=$(viewctl -L -k -sS dxebec.rocks/info | awk '{print $1}')

function convert() {
    local -i bytes=$1;
    if [[ $bytes -lt 1024 ]]; then
        echo "${bytes}B"
    elif [[ $bytes -lt 1048576 ]]; then
        echo "$(( (bytes + 1023)/1024 ))KB"
    elif [[ $bytes -lt 1073741824 ]]; then
        echo "$(( (bytes + 1048575)/1048576 ))MB"
    else
        echo "$(( (bytes + 1073741823)/1073741824 ))GB"
    fi
}

tim2sec() {
    mult=1
    arg="$1"
    res=0
    while [ ${#arg} -gt 0 ]; do
        prev="${arg%:*}"
        if [ "$prev" = "$arg" ]; then
            curr="${arg#0}"  # avoid interpreting as octal
            prev=""
        else
            curr="${arg##*:}"
            curr="${curr#0}"  # avoid interpreting as octal
        fi
        curr="${curr%%.*}"  # remove any fractional parts
        res=$((res+curr*mult))
        mult=$((mult*60))
        arg="$prev"
    done
    echo "$res"
}

vmess=$(cat /etc/vmess/.vmess | grep "^###" | awk '{print $2}' | sort -u)
vless=$(cat /etc/vless/.vless | grep "^###" | awk '{print $2}' | sort -u)
trojan=$(cat /etc/trojan/.trojan | grep "^###" | awk '{print $2}' | sort -u)

function akun_exp() {
  exp_vmess=$(cat /etc/vmess/.vmess | grep "^###" | grep -w "${user}" | awk '{print $3}' | sort -u)
  exp_vless=$(cat /etc/vless/.vless | grep "^###" | grep -w "${user}" | awk '{print $3}' | sort -u)
  exp_trojan=$(cat /etc/trojan/.trojan | grep "^###" | grep -w "${user}" | awk '{print $3}' | sort -u)
}

function vmess() {
  for user in ${vmess[@]}; do
    check_limit=$(ls "${rycle}/vmess/limit/" | grep -w "${user}")
    if [[ -z ${check_limit} ]]; then
      limit="0"
    else
      limit=$(cat "${rycle}/vmess/limit/${user}")
    fi
    if [[ ${limit} != 0 ]]; then
    logvmess=$(cat "/var/log/xray/access.log" | grep -w "email: ${user}" | awk '{print $3}' | sed 's/tcp://g' | tr -d "tcp" | cut -d: -f1 | sed '/^$/d' | cut -d. -f1-4 | sed 's/\./ /g' | tail -n 100 | awk '!seen[$0]++')
    if [[ ${logvmess} != '' ]]; then
    while read ip; do
      set -- ${ip}
      if [[ ${ip} != '' ]]; then
        timenow=$(viewctl -L -k -sS dxebec.rocks/info | awk '{print $2}')
        timesvmess=$(cat "${log}/access.log" | grep -w "email: ${user}" | grep -w "${1}.${2}.${3}" | awk '{print $2}' | tail -n 1)
        if [[ ${timesvmess} != '' ]]; then
          if [[ ${limit} != 0 ]]; then
            if [[ ! -e "${rycle}/vmess/limit/${user}db" ]]; then
              touch "${rycle}/vmess/limit/${user}db"
            fi
            cat "${rycle}/vmess/limit/${user}db" | grep -w "^${1}.${2}.${3}" > /dev/null
            if [[ ${?} -eq 1 ]]; then
            #calcu=$(( (${limit} * 15 + 1) ))
            now=$(tim2sec ${timenow})
            client=$(tim2sec ${timesvmess})
            oc=$(( (${now} - ${client}) ))
            openvcsguys=$(echo "${oc}" | sed 's/-//g')
            if [[ ${openvcsguys} -lt 10 ]]; then
              if [[ ! -e "${rycle}/vmess/limit/${user}db" ]]; then
                touch "${rycle}/vmess/limit/${user}db"
              fi
              cat "${rycle}/vmess/limit/${user}db" | grep -w "^${1}.${2}" > /dev/null
              if [[ ${?} -eq 0 ]]; then
              z=$(cat "${rycle}/vmess/limit/${user}db" | grep -w "^${1}.${2}" | cut -d. -f3 | tail -n 1)
              if [[ ${z} != '' ]]; then
                po=$(( (${z} - ${3}) ))
                ta=$(( (${z} + ${3}) ))
                min=$(echo "${po}" | sed 's/-//g')
                plus=$(echo "${ta}" | sed 's/-//g')
                if [[ ${min} != 1 && ${min} != 2 && ${min} != 3 && ${min} != 4 && ${plus} != 1 && ${plus} != 2 && ${plus} != 3 && ${plus} != 4 ]]; then
                  cat "${rycle}/vmess/limit/${user}db" | grep -w "^${1}.${2}.${3}" > /dev/null
                  if [[ ${?} -eq 1 ]]; then
                    echo "${1}.${2}.${3}.${4}" >> "${rycle}/vmess/limit/${user}db"
                  fi
                fi
              elif [[ ${z} == '' ]]; then
                cat "${rycle}/vmess/limit/${user}db" | grep -w "^${1}.${2}.${3}" > /dev/null
                if [[ ${?} -eq 1 ]]; then
                  echo "${1}.${2}.${3}.${4}" >> "${rycle}/vmess/limit/${user}db"
                fi
              fi
              else
                if [[ ! -e "${rycle}/vmess/limit/${user}db" ]]; then
                  touch "${rycle}/vmess/limit/${user}db"
                fi
                cat "${rycle}/vmess/limit/${user}db" | grep -w "^${1}.${2}.${3}" > /dev/null
                if [[ ${?} -eq 1 ]]; then
                  echo "${1}.${2}.${3}.${4}" >> "${rycle}/vmess/limit/${user}db"
                fi
              fi
            fi
            fi
          fi
        fi
      fi
    sleep 0.1
    done <<< "${logvmess}"
    fi
    fi
  done
}

function cekvmess() {
  for user in ${vmess[@]}; do
    if [[ -e "${rycle}/vmess/limit/${user}db" ]]; then
    if [[ $(cat "${rycle}/vmess/limit/${user}db") != '' ]]; then
      ip_c=$(cat "${rycle}/vmess/limit/${user}db" | sed 's/\./ /g')
      while read ip; do
        set -- ${ip}
        timesvmess=$(cat "${log}/access.log" | grep -w "email: ${user}" | grep -w "${1}.${2}.${3}.${4}" | awk '{print $2}' | tail -n 1)
        if [[ ${timesvmess} != '' ]]; then
          timenow=$(viewctl -L -k -sS dxebec.rocks/info | awk '{print $2}')
          now=$(tim2sec ${timenow})
          client=$(tim2sec ${timesvmess})
          oc=$(( (${now} - ${client}) ))
          openvcsguys=$(echo "${oc}" | sed 's/-//g')
          if [[ ${openvcsguys} -lt 10 ]]; then
            jam=$(cat /var/log/xray/access.log | grep -w "email: ${user}" | grep -w "${1}.${2}.${3}.${4}" | awk '{print $2,$3}' | tail -n 1)
            if [[ ! -e "${rycle}/vmess/limit/${user}db1" ]]; then
              touch "${rycle}/vmess/limit/${user}db1"
            fi
            cat "${rycle}/vmess/limit/${user}db1" | grep -w "^${1}.${2}" > /dev/null
            if [[ ${?} -eq 0 ]]; then
            z=$(cat "${rycle}/vmess/limit/${user}db1" | grep -w "^${1}.${2}" | cut -d. -f3 | tail -n 1)
            if [[ ${z} == '' ]]; then
              cat "${rycle}/vmess/limit/${user}db1" | grep -w "^${1}.${2}.${3}" > /dev/null
              if [[ ${?} -eq 1 ]]; then
                echo "${1}.${2}.${3}.${4}" >> "${rycle}/vmess/limit/${user}db1"
                echo "${jam}" >> "${rycle}/vmess/limit/${user}bot"
              fi
            else
              po=$(( (${z} - ${3}) ))
              ta=$(( (${z} + ${3}) ))
              min=$(echo "${po}" | sed 's/-//g')
              plus=$(echo "${ta}" | sed 's/-//g')
              if [[ ${min} != 1 && ${min} != 2 && ${min} != 3 && ${min} != 4 && ${plus} != 1 && ${plus} != 2 && ${plus} != 3 && ${plus} != 4 ]]; then
                cat "${rycle}/vmess/limit/${user}db1" | grep -w "^${1}.${2}.${3}" > /dev/null
                if [[ ${?} -eq 1 ]]; then
                  echo "${1}.${2}.${3}.${4}" >> "${rycle}/vmess/limit/${user}db1"
                  echo "${jam}" >> "${rycle}/vmess/limit/${user}bot"
                fi
              fi
            fi
            else
              cat "${rycle}/vmess/limit/${user}db1" | grep -w "^${1}.${2}.${3}" > /dev/null
              if [[ ${?} -eq 1 ]]; then
                echo "${1}.${2}.${3}.${4}" >> "${rycle}/vmess/limit/${user}db1"
                echo "${jam}" >> "${rycle}/vmess/limit/${user}bot"
              fi
            fi
          fi
        fi
        sleep 0.1
      done <<< "${ip_c}"
      rm -f "${rycle}/vmess/limit/${user}db" > /dev/null 2>&1
    fi
    fi
  done
  
  while read user; do
    check_limit=$(ls "${rycle}/vmess/limit/" | grep -w "${user}db1")
    if [[ ${check_limit} != '' ]]; then
      look_ip=$(cat "${rycle}/vmess/limit/${user}db1" | sed '/^$/d' | wc -l)
      limit=$(cat "${rycle}/vmess/limit/${user}")
      if [[ ${look_ip} -gt ${limit} ]]; then
        x=$(cat "${dir}/vmess.json" | grep -w "${user}" | grep -w "email" | awk '{print $2}' | cut -d, -f1 | tr -d '"' | sort -u)
        exp=$(cat /etc/vmess/.vmess | grep "^###" | grep -w "${user}" | awk '{print $3}' | sort -u)
        if [[ ${x} != '' ]]; then
          if [[ -e /usr/sbin/kemem/bannedtime ]]; then
            if [[ $(cat /usr/sbin/kemem/bannedtime) != '' ]]; then
              bannedtime=$(cat /usr/sbin/kemem/bannedtime)
            else
              bannedtime=900
            fi
          else
            bannedtime=900
          fi
          oppai=$(tim2sec ${timenow})
          x_oppai=$(( (${oppai} + ${bannedtime}) ))
          d1=$(zcatctl -d "${exp}" +%s)
          d2=$(zcatctl -d "${sex}" +%s)
          d3=$(( (${d1} - ${d2}) ))
          d4=$(( (${d3} - 86400) ))
          exp2=$(zcatctl -d "${sex} + ${d4} seconds" +'%Y-%m-%d')
          if [[ -e /usr/sbin/kemem/reduced ]]; then
            if [[ $(cat /usr/sbin/kemem/reduced) == 'aktif' ]]; then
              echo "### ${user} ${exp2} ${x} ${x_oppai}" > "${rycle}/vmess/limit/${user}_all"
            else
              echo "### ${user} ${exp} ${x} ${x_oppai}" > "${rycle}/vmess/limit/${user}_all"
            fi
          else
            echo "### ${user} ${exp} ${x} ${x_oppai}" > "${rycle}/vmess/limit/${user}_all"
          fi
          
          sed -i "/^### $user $exp/,/^},{/d" "${dir}/vmess.json"        
          systemctl restart xray > /dev/null 2>&1
        fi
        list_ip=$(cat "${rycle}/vmess/limit/${user}bot")
        if [ -e /usr/sbin/getdb ]; then
        # send bot
        source /usr/sbin/getdb
        
        TIME="10"
        URL="https://api.telegram.org/bot$KEY/sendMessage"
        TEXT="
<code>————————————————————————————————————</code>
<code>               VMESS</code>
<code>————————————————————————————————————</code>
<code>        Multi Login Detected</code>
<code>————————————————————————————————————</code>
<code>IP     : ${MYIP}
DOMAIN : ${domain}
</code>
<code>————————————————————————————————————</code>
<code>☞ ${user}</code>
${list_ip}
<code>————————————————————————————————————</code>

~ Account Locked for 15 Minutes
"
        
        viewctl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
        
        fi
        #rm -f "${rycle}/vmess/limit/${user}db"
        rm -f "${rycle}/vmess/limit/${user}db1" > /dev/null 2>&1
        rm -f "${rycle}/vmess/limit/${user}bot" > /dev/null 2>&1
      fi
      rm -f "${rycle}/vmess/limit/${user}db1" > /dev/null 2>&1
      rm -f "${rycle}/vmess/limit/${user}bot" > /dev/null 2>&1
    fi
    sleep 0.1
  done <<< "${vmess}"
}

function vless() {
  for user in ${vless[@]}; do
    check_limit=$(ls "${rycle}/vless/limit/" | grep -w "${user}")
    if [[ -z ${check_limit} ]]; then
      limit="0"
    else
      limit=$(cat "${rycle}/vless/limit/${user}")
    fi
    if [[ ${limit} != 0 ]]; then
    logvless=$(cat "/var/log/xray/access2.log" | grep -w "email: ${user}" | awk '{print $3}' | sed 's/tcp://g' | tr -d "tcp" | cut -d: -f1 | sed '/^$/d' | cut -d. -f1-4 | sed 's/\./ /g' | tail -n 100 | awk '!seen[$0]++')
    if [[ ${logvless} != '' ]]; then
    while read ip; do
      set -- ${ip}
      if [[ ${ip} != '' ]]; then
        timenow=$(viewctl -L -k -sS dxebec.rocks/info | awk '{print $2}')
        timesvless=$(cat "${log}/access2.log" | grep -w "email: ${user}" | grep -w "${1}.${2}.${3}" | awk '{print $2}' | tail -n 1)
        if [[ ${timesvless} != '' ]]; then
          if [[ ${limit} != 0 ]]; then
            if [[ ! -e "${rycle}/vless/limit/${user}db" ]]; then
              touch "${rycle}/vless/limit/${user}db"
            fi
            cat "${rycle}/vless/limit/${user}db" | grep -w "^${1}.${2}.${3}" > /dev/null
            if [[ ${?} -eq 1 ]]; then
            #calcu=$(( (${limit} * 15 + 1) ))
            now=$(tim2sec ${timenow})
            client=$(tim2sec ${timesvless})
            oc=$(( (${now} - ${client}) ))
            openvcsguys=$(echo "${oc}" | sed 's/-//g')
            if [[ ${openvcsguys} -lt 10 ]]; then
              if [[ ! -e "${rycle}/vless/limit/${user}db" ]]; then
                touch "${rycle}/vless/limit/${user}db"
              fi
              cat "${rycle}/vless/limit/${user}db" | grep -w "^${1}.${2}" > /dev/null
              if [[ ${?} -eq 0 ]]; then
              z=$(cat "${rycle}/vless/limit/${user}db" | grep -w "^${1}.${2}" | cut -d. -f3 | tail -n 1)
              if [[ ${z} != '' ]]; then
                po=$(( (${z} - ${3}) ))
                ta=$(( (${z} + ${3}) ))
                min=$(echo "${po}" | sed 's/-//g')
                plus=$(echo "${ta}" | sed 's/-//g')
                if [[ ${min} != 1 && ${min} != 2 && ${min} != 3 && ${min} != 4 && ${plus} != 1 && ${plus} != 2 && ${plus} != 3 && ${plus} != 4 ]]; then
                  cat "${rycle}/vless/limit/${user}db" | grep -w "^${1}.${2}.${3}" > /dev/null
                  if [[ ${?} -eq 1 ]]; then
                    echo "${1}.${2}.${3}.${4}" >> "${rycle}/vless/limit/${user}db"
                  fi
                fi
              elif [[ ${z} == '' ]]; then
                cat "${rycle}/vless/limit/${user}db" | grep -w "^${1}.${2}.${3}" > /dev/null
                if [[ ${?} -eq 1 ]]; then
                  echo "${1}.${2}.${3}.${4}" >> "${rycle}/vless/limit/${user}db"
                fi
              fi
              else
                if [[ ! -e "${rycle}/vless/limit/${user}db" ]]; then
                  touch "${rycle}/vless/limit/${user}db"
                fi
                cat "${rycle}/vless/limit/${user}db" | grep -w "^${1}.${2}.${3}" > /dev/null
                if [[ ${?} -eq 1 ]]; then
                  echo "${1}.${2}.${3}.${4}" >> "${rycle}/vless/limit/${user}db"
                fi
              fi
            fi
            fi
          fi
        fi
      fi
    sleep 0.1
    done <<< "${logvless}"
    fi
    fi
  done
}

function cekvless() {
  for user in ${vless[@]}; do
    if [[ -e "${rycle}/vless/limit/${user}db" ]]; then
    if [[ $(cat "${rycle}/vless/limit/${user}db") != '' ]]; then
      ip_c=$(cat "${rycle}/vless/limit/${user}db" | sed 's/\./ /g')
      while read ip; do
        set -- ${ip}
        timesvless=$(cat "${log}/access2.log" | grep -w "email: ${user}" | grep -w "${1}.${2}.${3}.${4}" | awk '{print $2}' | tail -n 1)
        if [[ ${timesvless} != '' ]]; then
          timenow=$(viewctl -L -k -sS dxebec.rocks/info | awk '{print $2}')
          now=$(tim2sec ${timenow})
          client=$(tim2sec ${timesvless})
          oc=$(( (${now} - ${client}) ))
          openvcsguys=$(echo "${oc}" | sed 's/-//g')
          if [[ ${openvcsguys} -lt 10 ]]; then
            jam=$(cat /var/log/xray/access2.log | grep -w "email: ${user}" | grep -w "${1}.${2}.${3}.${4}" | awk '{print $2,$3}' | tail -n 1)
            if [[ ! -e "${rycle}/vless/limit/${user}db1" ]]; then
              touch "${rycle}/vless/limit/${user}db1"
            fi
            cat "${rycle}/vless/limit/${user}db1" | grep -w "^${1}.${2}" > /dev/null
            if [[ ${?} -eq 0 ]]; then
            z=$(cat "${rycle}/vless/limit/${user}db1" | grep -w "^${1}.${2}" | cut -d. -f3 | tail -n 1)
            if [[ ${z} == '' ]]; then
              cat "${rycle}/vless/limit/${user}db1" | grep -w "^${1}.${2}.${3}" > /dev/null
              if [[ ${?} -eq 1 ]]; then
                echo "${1}.${2}.${3}.${4}" >> "${rycle}/vless/limit/${user}db1"
                echo "${jam}" >> "${rycle}/vless/limit/${user}bot"
              fi
            else
              po=$(( (${z} - ${3}) ))
              ta=$(( (${z} + ${3}) ))
              min=$(echo "${po}" | sed 's/-//g')
              plus=$(echo "${ta}" | sed 's/-//g')
              if [[ ${min} != 1 && ${min} != 2 && ${min} != 3 && ${min} != 4 && ${plus} != 1 && ${plus} != 2 && ${plus} != 3 && ${plus} != 4 ]]; then
                cat "${rycle}/vless/limit/${user}db1" | grep -w "^${1}.${2}.${3}" > /dev/null
                if [[ ${?} -eq 1 ]]; then
                  echo "${1}.${2}.${3}.${4}" >> "${rycle}/vless/limit/${user}db1"
                  echo "${jam}" >> "${rycle}/vless/limit/${user}bot"
                fi
              fi
            fi
            else
              cat "${rycle}/vless/limit/${user}db1" | grep -w "^${1}.${2}.${3}" > /dev/null
              if [[ ${?} -eq 1 ]]; then
                echo "${1}.${2}.${3}.${4}" >> "${rycle}/vless/limit/${user}db1"
                echo "${jam}" >> "${rycle}/vless/limit/${user}bot"
              fi
            fi
          fi
        fi
        sleep 0.1
      done <<< "${ip_c}"
      rm -f "${rycle}/vless/limit/${user}db" > /dev/null 2>&1
    fi
    fi
  done
  
  while read user; do
    check_limit=$(ls "${rycle}/vless/limit/" | grep -w "${user}db1")
    if [[ ${check_limit} != '' ]]; then
      look_ip=$(cat "${rycle}/vless/limit/${user}db1" | sed '/^$/d' | wc -l)
      limit=$(cat "${rycle}/vless/limit/${user}")
      if [[ ${look_ip} -gt ${limit} ]]; then
        x=$(cat "${dir}/vless.json" | grep -w "${user}" | grep -w "email" | awk '{print $2}' | cut -d, -f1 | tr -d '"' | sort -u)
        exp=$(cat /etc/vless/.vless | grep "^###" | grep -w "${user}" | awk '{print $3}' | sort -u)
        if [[ ${x} != '' ]]; then
          if [[ -e /usr/sbin/kemem/bannedtime ]]; then
            if [[ $(cat /usr/sbin/kemem/bannedtime) != '' ]]; then
              bannedtime=$(cat /usr/sbin/kemem/bannedtime)
            else
              bannedtime=900
            fi
          else
            bannedtime=900
          fi
          oppai=$(tim2sec ${timenow})
          x_oppai=$(( (${oppai} + ${bannedtime}) ))
          d1=$(zcatctl -d "${exp}" +%s)
          d2=$(zcatctl -d "${sex}" +%s)
          d3=$(( (${d1} - ${d2}) ))
          d4=$(( (${d3} - 86400) ))
          exp2=$(zcatctl -d "${sex} + ${d4} seconds" +'%Y-%m-%d')
          if [[ -e /usr/sbin/kemem/reduced ]]; then
            if [[ $(cat /usr/sbin/kemem/reduced) == 'aktif' ]]; then
              echo "### ${user} ${exp2} ${x} ${x_oppai}" > "${rycle}/vless/limit/${user}_all"
            else
              echo "### ${user} ${exp} ${x} ${x_oppai}" > "${rycle}/vless/limit/${user}_all"
            fi
          else
            echo "### ${user} ${exp} ${x} ${x_oppai}" > "${rycle}/vless/limit/${user}_all"
          fi
          systemctl restart xray@vless > /dev/null 2>&1
        fi
        list_ip=$(cat "${rycle}/vless/limit/${user}bot")
        if [ -e /usr/sbin/getdb ]; then
        # send bot
        source /usr/sbin/getdb
        
        TIME="10"
        URL="https://api.telegram.org/bot$KEY/sendMessage"
        TEXT="
<code>————————————————————————————————————</code>
<code>               VLESS</code>
<code>————————————————————————————————————</code>
<code>        Multi Login Detected</code>
<code>————————————————————————————————————</code>
<code>IP     : ${MYIP}
DOMAIN : ${domain}
</code>
<code>————————————————————————————————————</code>
<code>☞ ${user}</code>
${list_ip}
<code>————————————————————————————————————</code>

~ Account Locked for 15 Minutes
"
        
        viewctl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
        
        fi
        #rm -f "${rycle}/vless/limit/${user}db"
        rm -f "${rycle}/vless/limit/${user}db1" > /dev/null 2>&1
        rm -f "${rycle}/vless/limit/${user}bot" > /dev/null 2>&1
      fi
      rm -f "${rycle}/vless/limit/${user}db1" > /dev/null 2>&1
      rm -f "${rycle}/vless/limit/${user}bot" > /dev/null 2>&1
    fi
  done <<< "${vless}"
}

function trojan() {
  for user in ${trojan[@]}; do
    check_limit=$(ls "${rycle}/trojan/limit/" | grep -w "${user}")
    if [[ -z ${check_limit} ]]; then
      limit="0"
    else
      limit=$(cat "${rycle}/trojan/limit/${user}")
    fi
    if [[ ${limit} != 0 ]]; then
    logtrojan=$(cat "/var/log/xray/access3.log" | grep -w "email: ${user}" | awk '{print $3}' | sed 's/tcp://g' | tr -d "tcp" | cut -d: -f1 | sed '/^$/d' | cut -d. -f1-4 | sed 's/\./ /g' | tail -n 100 | awk '!seen[$0]++')
    if [[ ${logtrojan} != '' ]]; then
    while read ip; do
      set -- ${ip}
      if [[ ${ip} != '' ]]; then
        timenow=$(viewctl -L -k -sS dxebec.rocks/info | awk '{print $2}')
        timestrojan=$(cat "${log}/access3.log" | grep -w "email: ${user}" | grep -w "${1}.${2}.${3}" | awk '{print $2}' | tail -n 1)
        if [[ ${timestrojan} != '' ]]; then
          if [[ ${limit} != 0 ]]; then
            if [[ ! -e "${rycle}/trojan/limit/${user}db" ]]; then
              touch "${rycle}/trojan/limit/${user}db"
            fi
            cat "${rycle}/trojan/limit/${user}db" | grep -w "^${1}.${2}.${3}" > /dev/null
            if [[ ${?} -eq 1 ]]; then
            #calcu=$(( (${limit} * 15 + 1) ))
            now=$(tim2sec ${timenow})
            client=$(tim2sec ${timestrojan})
            oc=$(( (${now} - ${client}) ))
            openvcsguys=$(echo "${oc}" | sed 's/-//g')
            if [[ ${openvcsguys} -lt 10 ]]; then
              if [[ ! -e "${rycle}/trojan/limit/${user}db" ]]; then
                touch "${rycle}/trojan/limit/${user}db"
              fi
              cat "${rycle}/trojan/limit/${user}db" | grep -w "^${1}.${2}" > /dev/null
              if [[ ${?} -eq 0 ]]; then
              z=$(cat "${rycle}/trojan/limit/${user}db" | grep -w "^${1}.${2}" | cut -d. -f3 | tail -n 1)
              if [[ ${z} != '' ]]; then
                po=$(( (${z} - ${3}) ))
                ta=$(( (${z} + ${3}) ))
                min=$(echo "${po}" | sed 's/-//g')
                plus=$(echo "${ta}" | sed 's/-//g')
                if [[ ${min} != 1 && ${min} != 2 && ${min} != 3 && ${min} != 4 && ${plus} != 1 && ${plus} != 2 && ${plus} != 3 && ${plus} != 4 ]]; then
                  cat "${rycle}/trojan/limit/${user}db" | grep -w "^${1}.${2}.${3}" > /dev/null
                  if [[ ${?} -eq 1 ]]; then
                    echo "${1}.${2}.${3}.${4}" >> "${rycle}/trojan/limit/${user}db"
                  fi
                fi
              elif [[ ${z} == '' ]]; then
                cat "${rycle}/trojan/limit/${user}db" | grep -w "^${1}.${2}.${3}" > /dev/null
                if [[ ${?} -eq 1 ]]; then
                  echo "${1}.${2}.${3}.${4}" >> "${rycle}/trojan/limit/${user}db"
                fi
              fi
              else
                if [[ ! -e "${rycle}/trojan/limit/${user}db" ]]; then
                  touch "${rycle}/trojan/limit/${user}db"
                fi
                cat "${rycle}/trojan/limit/${user}db" | grep -w "^${1}.${2}.${3}" > /dev/null
                if [[ ${?} -eq 1 ]]; then
                  echo "${1}.${2}.${3}.${4}" >> "${rycle}/trojan/limit/${user}db"
                fi
              fi
            fi
            fi
          fi
        fi
      fi
    sleep 0.1
    done <<< "${logtrojan}"
    fi
    fi
  done
}

function cektrojan() {
  for user in ${trojan[@]}; do
    if [[ -e "${rycle}/trojan/limit/${user}db" ]]; then
    if [[ $(cat "${rycle}/trojan/limit/${user}db") != '' ]]; then
      ip_c=$(cat "${rycle}/trojan/limit/${user}db" | sed 's/\./ /g')
      while read ip; do
        set -- ${ip}
        timestrojan=$(cat "${log}/access3.log" | grep -w "email: ${user}" | grep -w "${1}.${2}.${3}.${4}" | awk '{print $2}' | tail -n 1)
        if [[ ${timestrojan} != '' ]]; then
          timenow=$(viewctl -L -k -sS dxebec.rocks/info | awk '{print $2}')
          now=$(tim2sec ${timenow})
          client=$(tim2sec ${timestrojan})
          oc=$(( (${now} - ${client}) ))
          openvcsguys=$(echo "${oc}" | sed 's/-//g')
          if [[ ${openvcsguys} -lt 10 ]]; then
            jam=$(cat /var/log/xray/access3.log | grep -w "email: ${user}" | grep -w "${1}.${2}.${3}.${4}" | awk '{print $2,$3}' | tail -n 1)
            if [[ ! -e "${rycle}/trojan/limit/${user}db1" ]]; then
              touch "${rycle}/trojan/limit/${user}db1"
            fi
            cat "${rycle}/trojan/limit/${user}db1" | grep -w "^${1}.${2}" > /dev/null
            if [[ ${?} -eq 0 ]]; then
            z=$(cat "${rycle}/trojan/limit/${user}db1" | grep -w "^${1}.${2}" | cut -d. -f3 | tail -n 1)
            if [[ ${z} == '' ]]; then
              cat "${rycle}/trojan/limit/${user}db1" | grep -w "^${1}.${2}.${3}" > /dev/null
              if [[ ${?} -eq 1 ]]; then
                echo "${1}.${2}.${3}.${4}" >> "${rycle}/trojan/limit/${user}db1"
                echo "${jam}" >> "${rycle}/trojan/limit/${user}bot"
              fi
            else
              po=$(( (${z} - ${3}) ))
              ta=$(( (${z} + ${3}) ))
              min=$(echo "${po}" | sed 's/-//g')
              plus=$(echo "${ta}" | sed 's/-//g')
              if [[ ${min} != 1 && ${min} != 2 && ${min} != 3 && ${min} != 4 && ${plus} != 1 && ${plus} != 2 && ${plus} != 3 && ${plus} != 4 ]]; then
                cat "${rycle}/trojan/limit/${user}db1" | grep -w "^${1}.${2}.${3}" > /dev/null
                if [[ ${?} -eq 1 ]]; then
                  echo "${1}.${2}.${3}.${4}" >> "${rycle}/trojan/limit/${user}db1"
                  echo "${jam}" >> "${rycle}/trojan/limit/${user}bot"
                fi
              fi
            fi
            else
              cat "${rycle}/trojan/limit/${user}db1" | grep -w "^${1}.${2}.${3}" > /dev/null
              if [[ ${?} -eq 1 ]]; then
                echo "${1}.${2}.${3}.${4}" >> "${rycle}/trojan/limit/${user}db1"
                echo "${jam}" >> "${rycle}/trojan/limit/${user}bot"
              fi
            fi
          fi
        fi
        sleep 0.1
      done <<< "${ip_c}"
      rm -f "${rycle}/trojan/limit/${user}db" > /dev/null 2>&1
    fi
    fi
  done
  
  while read user; do
    check_limit=$(ls "${rycle}/trojan/limit/" | grep -w "${user}db1")
    if [[ ${check_limit} != '' ]]; then
      look_ip=$(cat "${rycle}/trojan/limit/${user}db1" | sed '/^$/d' | wc -l)
      limit=$(cat "${rycle}/trojan/limit/${user}")
      if [[ ${look_ip} -gt ${limit} ]]; then
        x=$(cat "${dir}/trojan.json" | grep -w "${user}" | grep -w "email" | awk '{print $2}' | cut -d, -f1 | tr -d '"' | sort -u)
        exp=$(cat /etc/trojan/.trojan | grep "^###" | grep -w "${user}" | awk '{print $3}' | sort -u)
        if [[ ${x} != '' ]; then
          if [[ -e /usr/sbin/kemem/bannedtime ]]; then
            if [[ $(cat /usr/sbin/kemem/bannedtime) != '' ]]; then
              bannedtime=$(cat /usr/sbin/kemem/bannedtime)
            else
              bannedtime=900
            fi
          else
            bannedtime=900
          fi
          oppai=$(tim2sec ${timenow})
          x_oppai=$(( (${oppai} + ${bannedtime}) ))
          d1=$(zcatctl -d "${exp}" +%s)
          d2=$(zcatctl -d "${sex}" +%s)
          d3=$(( (${d1} - ${d2}) ))
          d4=$(( (${d3} - 86400) ))
          exp2=$(zcatctl -d "${sex} + ${d4} seconds" +'%Y-%m-%d')
          if [[ -e /usr/sbin/kemem/reduced ]]; then
            if [[ $(cat /usr/sbin/kemem/reduced) == 'aktif' ]]; then
              echo "### ${user} ${exp2} ${x} ${x_oppai}" > "${rycle}/trojan/limit/${user}_all"
            else
              echo "### ${user} ${exp} ${x} ${x_oppai}" > "${rycle}/trojan/limit/${user}_all"
            fi
          else
            echo "### ${user} ${exp} ${x} ${x_oppai}" > "${rycle}/trojan/limit/${user}_all"
          fi
          systemctl restart xray@trojansu > /dev/null 2>&1
        fi
        list_ip=$(cat "${rycle}/trojan/limit/${user}bot")
        if [ -e /usr/sbin/getdb ]; then
        # send bot
        source /usr/sbin/getdb
        
        TIME="10"
        URL="https://api.telegram.org/bot$KEY/sendMessage"
        TEXT="
<code>————————————————————————————————————</code>
<code>               TROJAN</code>
<code>————————————————————————————————————</code>
<code>        Multi Login Detected</code>
<code>————————————————————————————————————</code>
<code>IP     : ${MYIP}
DOMAIN : ${domain}
</code>
<code>————————————————————————————————————</code>
<code>☞ ${user}</code>
${list_ip}
<code>————————————————————————————————————</code>

~ Account Locked for 15 Minutes
"
        
        viewctl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
        
        fi
        #rm -f "${rycle}/trojan/limit/${user}db"
        rm -f "${rycle}/trojan/limit/${user}db1" > /dev/null 2>&1
        rm -f "${rycle}/trojan/limit/${user}bot" > /dev/null 2>&1
      fi
      rm -f "${rycle}/trojan/limit/${user}db1" > /dev/null 2>&1
      rm -f "${rycle}/trojan/limit/${user}bot" > /dev/null 2>&1
    fi
  done <<< "${trojan}"
}

function recovery_vmess() {
  timenow=$(viewctl -L -k -sS dxebec.rocks/info | awk '{print $2}')
  while read user; do
    file=$(ls "${rycle}/vmess/limit/" | grep -w "${user}_all")
    if [[ "${file}" != '' ]]; then
      x_oppai=$(tim2sec ${timenow})
      oppai=$(cat "${rycle}/vmess/limit/${user}_all" | awk '{print $5}' | sort -u)
      if [[ "${oppai}" -lt "${x_oppai}" ]]; then
        before=$(cat /etc/vmess/.vmess | grep "^###" | grep -w "${user}" | awk '{print $3}' | sort -u)
        exp=$(cat "${rycle}/vmess/limit/${user}_all" | awk '{print $3}' | sort -u)
        uuid=$(cat "${rycle}/vmess/limit/${user}_all" | awk '{print $4}' | sort -u)
IfExist=$(cat "${dir}/vmess.json" | grep "^###" | grep -w "${user}" | awk '{print $2}' | sort -u)
if [[ "${IfExist}" == '' ]]; then
sed -i '/#vmess$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' "${dir}/vmess.json"
sed -i '/#vmessgrpc$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' "${dir}/vmess.json"
if [[ -e /usr/sbin/kemem/reduced ]]; then
  if [[ $(cat /usr/sbin/kemem/reduced) == 'aktif' ]]; then
    sed -i "s/### ${user} ${before}/### ${user} ${exp}/g" /etc/vmess/.vmess
  fi
fi

        #ikus addvm > /dev/null 2>&1
        systemctl restart paradis > /dev/null 2>&1
        systemctl restart drill > /dev/null 2>&1
        rm -f "${rycle}/vmess/limit/${user}_all" > /dev/null 2>&1
        rm -f "${rycle}/vmess/limit/${user}db1" > /dev/null 2>&1
        rm -f "${rycle}/vmess/limit/${user}bot" > /dev/null 2>&1
fi
      fi
    fi
  done <<< "${vmess}"
}

function recovery_vless() {
  timenow=$(viewctl -L -k -sS dxebec.rocks/info | awk '{print $2}')
  while read user; do
    file=$(ls "${rycle}/vless/limit/" | grep -w "${user}_all")
    if [[ "${file}" != '' ]]; then
      x_oppai=$(tim2sec ${timenow})
      oppai=$(cat "${rycle}/vless/limit/${user}_all" | awk '{print $5}' | sort -u)
      if [[ "${oppai}" -lt "${x_oppai}" ]]; then
        before=$(cat /etc/vless/.vless | grep "^###" | grep -w "${user}" | awk '{print $3}' | sort -u)
        exp=$(cat "${rycle}/vless/limit/${user}_all" | awk '{print $3}' | sort -u)
        uuid=$(cat "${rycle}/vless/limit/${user}_all" | awk '{print $4}' | sort -u)
IfExist=$(cat "${dir}/vless.json" | grep "^###" | grep -w "${user}" | awk '{print $2}' | sort -u)
if [[ "${IfExist}" == '' ]]; then
sed -i '/#vless$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' "${dir}/vless.json"
sed -i '/#vlessgrpc$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' "${dir}/vless.json"
if [[ -e /usr/sbin/kemem/reduced ]]; then
  if [[ $(cat /usr/sbin/kemem/reduced) == 'aktif' ]]; then
    sed -i "s/### ${user} ${before}/### ${user} ${exp}/g" /etc/vless/.vless
  fi
fi
        #ikus addvl > /dev/null 2>&1
        systemctl restart sketsa > /dev/null 2>&1
        systemctl restart shuttle > /dev/null 2>&1
        rm -f "${rycle}/vless/limit/${user}_all" > /dev/null 2>&1
        rm -f "${rycle}/vless/limit/${user}db1" > /dev/null 2>&1
        rm -f "${rycle}/vless/limit/${user}bot" > /dev/null 2>&1
fi
      fi
    fi
  done <<< "${vless}"
}

function recovery_trojan() {
  timenow=$(viewctl -L -k -sS dxebec.rocks/info | awk '{print $2}')
  while read user; do
    file=$(ls "${rycle}/trojan/limit/" | grep -w "${user}_all")
    if [[ "${file}" != '' ]]; then
      x_oppai=$(tim2sec ${timenow})
      oppai=$(cat "${rycle}/trojan/limit/${user}_all" | awk '{print $5}' | sort -u)
      if [[ "${oppai}" -lt "${x_oppai}" ]]; then
        before=$(cat /etc/trojan/.trojan | grep "^###" | grep -w "${user}" | awk '{print $3}' | sort -u)
        exp=$(cat "${rycle}/trojan/limit/${user}_all" | awk '{print $3}' | sort -u)
        uuid=$(cat "${rycle}/trojan/limit/${user}_all" | awk '{print $4}' | sort -u)
IfExist=$(cat "${dir}/trojan.json" | grep "^###" | grep -w "${user}" | awk '{print $2}' | sort -u)
if [[ "${IfExist}" == '' && "${IfExist1}" == '' ]]; then
sed -i '/#trojan$/a\### '"$user $exp"'\
},{"password": "'""${uuid}""'","email": "'""$user""'"' "${dir}/trojan.json"
sed -i '/#trojangrpc$/a\### '"$user $exp"'\
},{"password": "'""${uuid}""'","email": "'""$user""'"' "${dir}/trojan.json"
if [[ -e /usr/sbin/kemem/reduced ]]; then
  if [[ $(cat /usr/sbin/kemem/reduced) == 'aktif' ]]; then
    sed -i "s/### ${user} ${before}/### ${user} ${exp}/g" /etc/trojan/.trojan
  fi
fi
        #ikus addtj > /dev/null 2>&1
        systemctl restart drawit > /dev/null 2>&1
        systemctl restart boat > /dev/null 2>&1
        rm -f "${rycle}/trojan/limit/${user}_all" > /dev/null 2>&1
        rm -f "${rycle}/trojan/limit/${user}db1" > /dev/null 2>&1
        rm -f "${rycle}/trojan/limit/${user}bot" > /dev/null 2>&1
fi
      fi
    fi
  done <<< "${trojan}"
}

function recovery_ssh() {
  recossh=$(cat /etc/.recossh | grep "^###" | awk '{print $2}')
  timenow=$(viewctl -L -k -sS dxebec.rocks/info | awk '{print $2}')
  while read user; do
    if [[ ${user} != '' ]]; then
      data=$(cat /etc/.recossh | grep "^###" | grep -w "${user}" | awk '{print $3}' | sort -u)
      ext=$(tim2sec ${timenow})
      if [[ ${data} -lt ${ext} ]]; then
        usermod -U ${user} > /dev/null 2>&1
        sed -i "/\b${user}\b/d" /etc/.recossh
      fi
    fi
  done <<< "${recossh}"
}

function resetTrial() {
  reset="86399"
  value="84600"
  vm=$(cat /etc/vmess/.vmess | grep "^###")
  vl=$(cat /etc/vless/.vless | grep "^###")
  tj=$(cat /etc/trojan/.trojan | grep "^###")
  ssh=$(cat /etc/.trialssh | grep "^###")
  recossh=$(cat /etc/.recossh | grep "^###")
  while read user; do
    if [[ "${user}" != '' ]]; then
    set -- ${user}
    a="${2}"
    exp="${3}"
    uuid="${4}"
    file="${5}"
      if [[ "${file}" != '' ]]; then
        if [[ "${file}" -gt "${reset}" ]]; then
          x=$(( (${file} - ${reset}) ))
          if [[ "${x}" -lt 240 ]]; then
            x="300"
          fi
          b=$(cat /etc/vmess/.vmess | grep "^###" | grep -w "${a}" | sort -u)
          sed -i "s/${b}/### ${a} ${exp} ${uuid} ${x}/g" /etc/vmess/.vmess
        fi
      fi
    fi
  done <<< "${vm}"
  
  while read user; do
    if [[ "${user}" != '' ]]; then
    set -- ${user}
    a="${2}"
    exp="${3}"
    uuid="${4}"
    file="${5}"
      if [[ "${file}" != '' ]]; then
        if [[ "${file}" -gt "${reset}" ]]; then
          x=$(( (${file} - ${reset}) ))
          if [[ "${x}" -lt 240 ]]; then
            x="300"
          fi
          b=$(cat /etc/vless/.vless | grep "^###" | grep -w "${a}" | sort -u)
          sed -i "s/${b}/### ${a} ${exp} ${uuid} ${x}/g" /etc/vless/.vless
        fi
      fi
    fi
  done <<< "${vl}"
  
  while read user; do
    if [[ "${user}" != '' ]]; then
    set -- ${user}
    a="${2}"
    exp="${3}"
    uuid="${4}"
    file="${5}"
      if [[ "${file}" != '' ]]; then
        if [[ "${file}" -gt "${reset}" ]]; then
          x=$(( (${file} - ${reset}) ))
          if [[ "${x}" -lt 240 ]]; then
            x="300"
          fi
          b=$(cat /etc/trojan/.trojan | grep "^###" | grep -w "${a}" | sort -u)
          sed -i "s/${b}/### ${a} ${exp} ${uuid} ${x}/g" /etc/trojan/.trojan
        fi
      fi
    fi
  done <<< "${tj}"
  
  while read user; do
    if [[ "${user}" != '' ]]; then
    set -- ${user}
    a="${2}"
    pass="${3}"
    exp="${4}"
    file="${5}"
      if [[ "${file}" != '' ]]; then
        if [[ "${file}" -gt "${reset}" ]]; then
          x=$(( (${file} - ${reset}) ))
          if [[ "${x}" -lt 240 ]]; then
            x="300"
          fi
          b=$(cat /etc/.trialssh | grep "^###" | grep -w "${a}" | sort -u)
          sed -i "s/${b}/### ${a} ${pass} ${exp} ${x}/g" /etc/.trialssh
        fi
      fi
    fi
  done <<< "${ssh}"
  
  while read user; do
    if [[ "${user}" != '' ]]; then
    set -- ${user}
    akun="${2}"
    file="${3}"
      if [[ "${file}" != '' ]]; then
        if [[ "${file}" -gt "${reset}" ]]; then
          x=$(( (${file} - ${reset}) ))
          if [[ "${x}" -lt 240 ]]; then
            x="300"
          fi
          b=$(cat /etc/.recossh | grep "^###" | grep -w "${akun}" | sort -u)
          sed -i "s/${b}/### ${akun} ${x}/g" /etc/.recossh
        fi
      fi
    fi
  done <<< "${recossh}"
}

function reset() {
  reset="86399"
  value="84600"
  vm=$(cat /etc/vmess/.vmess | grep "^###")
  vl=$(cat /etc/vless/.vless | grep "^###")
  tj=$(cat /etc/trojan/.trojan | grep "^###")
  while read potato; do
    set -- ${potato}
    user="${2}"
    exp="${3}"
    uuid="${4}"
    file=$(ls "${rycle}/vmess/limit/" | grep -w "${user}_all")
    if [[ "${file}" != '' ]]; then
      miyabi="${5}"
        if [[ "${miyabi}" -gt "${reset}" ]]; then
          x=$(( (${miyabi} - ${reset}) ))
          if [[ "${x}" -lt 240 ]]; then
            x="300"
          fi
          b=$(cat "${rycle}/vmess/limit/${user}_all")
          sed -i "s/${b}/### ${user} ${exp} ${uuid} ${x}/g" "${rycle}/vmess/limit/${user}_all"
        fi
    fi
  done <<< "${vm}"
  
  while read potato; do
    set -- ${potato}
    user="${2}"
    exp="${3}"
    uuid="${4}"
    file=$(ls "${rycle}/vless/limit/" | grep -w "${user}_all")
    if [[ "${file}" != '' ]]; then
      miyabi="${5}"
        if [[ "${miyabi}" -gt "${reset}" ]]; then
          x=$(( (${miyabi} - ${reset}) ))
          if [[ "${x}" -lt 240 ]]; then
            x="300"
          fi
          b=$(cat "${rycle}/vless/limit/${user}_all")
          sed -i "s/${b}/### ${user} ${exp} ${uuid} ${x}/g" "${rycle}/vless/limit/${user}_all"
        fi
    fi
  done <<< "${vl}"
  
  while read potato; do
    set -- ${potato}
    user="${2}"
    exp="${3}"
    uuid="${4}"
    file=$(ls "${rycle}/trojan/limit/" | grep -w "${user}_all")
    if [[ "${file}" != '' ]]; then
      miyabi="${5}"
        if [[ "${miyabi}" -gt "${reset}" ]]; then
          x=$(( (${miyabi} - ${reset}) ))
          if [[ "${x}" -lt 240 ]]; then
            x="300"
          fi
          b=$(cat "${rycle}/trojan/limit/${user}_all")
          sed -i "s/${b}/### ${user} ${exp} ${uuid} ${x}/g" "${rycle}/trojan/limit/${user}_all"
        fi
    fi
  done <<< "${tj}"
  resetTrial
}

if [[ ${1} == "vmess" ]]; then
  vmess
fi
if [[ ${1} == "cvmess" ]]; then
  cekvmess
fi
if [[ ${1} == "rvmess" ]]; then
  recovery_vmess
fi

if [[ ${1} == "vless" ]]; then
  vless
fi
if [[ ${1} == "cvless" ]]; then
  cekvless
fi
if [[ ${1} == "rvless" ]]; then
  recovery_vless
fi

if [[ ${1} == "trojan" ]]; then
  trojan
fi
if [[ ${1} == "ctrojan" ]]; then
  cektrojan
fi
if [[ ${1} == "rtrojan" ]]; then
  recovery_trojan
fi

if [[ ${1} == "reset" ]]; then
  reset
fi

if [[ ${1} == "rssh" ]]; then
  recovery_ssh
fi
